server:
  address: 0.0.0.0:9091

log:
  level: info

theme: dark

jwt_secret: "REDACTED_JWT_SECRET"

default_redirection_url: "https://example.domain.com"

totp:
  issuer: "Example"
  period: 30

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 3
      memory: 65536
      parallelism: 4
      salt_length: 16
      key_length: 32

session:
  name: authelia_session
  secret: "REDACTED_SESSION_SECRET"
  expiration: 3600
  inactivity: 300
  domain: "example.com"
  same_site: lax

storage:
  local:
    path: /config/storage.sqlite3
  encryption_key: "REDACTED_STORAGE_KEY"

access_control:
  default_policy: deny
  rules:
    - domain: "*.example.com"
      policy: one_factor

notifier:
  disable_startup_check: true
  filesystem:
    filename: /config/notification.txt
